# Generated by Django 5.2.7 on 2026-09-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('menu', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('menu_view', 'Menu view'), ('language_change', 'Language change'), ('whatsapp_click', 'WhatsApp click'), ('phone_click', 'Phone click'), ('qr_open', 'QR scan')], max_length=30)),
                ('locale', models.CharField(default='tr', help_text='ISO code (tr/en). Unknown values pass through; validation lives in the API.', max_length=5)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent_hash', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(max_length=64)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_events', to='branches.branch')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_events', to='menu.menu')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Menü Görüntülenme Olayı',
                'verbose_name_plural': 'Menü Görüntülenme Olayları',
                'ordering': ('-created_at',),
            },
        ),
    ]
