# Generated by Django 5.2.7 on 2026-09-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuviewevent',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_events', to='qr.qrcode'),
        ),
        migrations.AddIndex(
            model_name='menuviewevent',
            index=models.Index(fields=['organization', '-created_at'], name='analytics_m_organiz_7c5be7_idx'),
        ),
        migrations.AddIndex(
            model_name='menuviewevent',
            index=models.Index(fields=['organization', 'event_type', '-created_at'], name='analytics_m_organiz_5871e1_idx'),
        ),
    ]
