# Generated by Django 5.2.7 on 2026-09-28 13:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lowercased on save; canonical sign-in identity.', max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive customers cannot authenticate or earn points.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email'], name='account_cus_email_32dadd_idx'), models.Index(fields=['-last_login_at'], name='account_cus_last_lo_47bfac_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. Off = no earn / redeem / balance.')),
                ('points_per_currency_unit', models.DecimalField(decimal_places=4, default=Decimal('1.00'), help_text='Earn rate: order.total_amount * this = points awarded.', max_digits=10)),
                ('redemption_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Redeem rate: points_to_redeem * this = discount (TL).', max_digits=10)),
                ('min_points_to_redeem', models.PositiveIntegerField(default=100, help_text='Minimum puan bakiyesi gerekli (e.g. 100).')),
                ('points_expiry_days', models.PositiveIntegerField(blank=True, help_text='Days before earned points expire. null = never expire.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sadakat Ayarları',
                'verbose_name_plural': 'Sadakat Ayarları',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire'), ('adjust', 'Adjust'), ('reverse', 'Reverse')], max_length=10)),
                ('points', models.IntegerField(help_text='Signed integer. Earn/reverse-of-redemption = +, redeem/expire/adjust-down = -.')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='account.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sadakat İşlemi',
                'verbose_name_plural': 'Sadakat İşlemleri',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer', '-created_at'], name='account_loy_custome_de30f1_idx'), models.Index(fields=['organization', 'type'], name='account_loy_organiz_7f3cb6_idx'), models.Index(fields=['organization', 'customer', '-created_at'], name='account_loy_organiz_d358d6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type', 'earn')), fields=('order', 'type'), name='unique_earn_per_order')],
            },
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='UUID4 hex. Stored once, invalidated on first use.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_tokens', to='account.customer')),
            ],
            options={
                'verbose_name': 'Magic Link Token',
                'verbose_name_plural': 'Magic Link Tokens',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['token', 'expires_at'], name='account_mag_token_57b6da_idx'), models.Index(fields=['customer', '-created_at'], name='account_mag_custome_ece988_idx')],
            },
        ),
    ]
