# Generated by Django 5.2.7 on 2026-09-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_customer'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(default='stripe', max_length=16)),
                ('provider_payment_id', models.CharField(max_length=128)),
                ('provider_payment_status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action (3DS)'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='requires_payment_method', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(choices=[('stripe', 'Stripe (primary — V1)'), ('iyzico', 'iyzico (V2 SaaS — placeholder)')], default='stripe', max_length=16)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('webhook_secret_encrypted', models.TextField(blank=True, default='')),
                ('is_test_mode', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_refund_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('duplicate', 'Duplicate charge'), ('fraudulent', 'Fraudulent')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='organizations.organization')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment.orderpayment')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=16)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_name', '-received_at'], name='payment_web_provide_832131_idx')],
                'unique_together': {('provider_name', 'provider_event_id')},
            },
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['organization', '-created_at'], name='payment_ord_organiz_1220fb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['provider_payment_id'], name='payment_ord_provide_be77bd_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['provider_payment_status'], name='payment_ord_provide_4f896b_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['organization', '-created_at'], name='payment_ref_organiz_897162_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['payment', '-created_at'], name='payment_ref_payment_ddb390_idx'),
        ),
    ]
