# Generated by Django 5.2.7 on 2026-09-26 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('menu', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, help_text="Human-readable id (e.g. 'MC-20260115-001'). Generated in services.generate_order_number().", max_length=30, unique=True)),
                ('table_number', models.CharField(blank=True, default='', max_length=20)),
                ('customer_name', models.CharField(max_length=80)),
                ('customer_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Beklemede (müşteri gönderdi)'), ('confirmed', 'Onaylandı (admin kabul etti)'), ('preparing', 'Hazırlanıyor (mutfak)'), ('ready', 'Hazır (müşteriye bildirildi)'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Server-computed sum of OrderItem.price * quantity (OP-6).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='branches.branch')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.menu')),
                ('organization', models.ForeignKey(help_text='Tenant scope. PROTECT prevents accidental org deletes.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ('-placed_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, help_text='Snapshot of MenuItem.price at order time (OP-6).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', '-placed_at'], name='orders_orde_organiz_3c40fa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status'], name='orders_orde_organiz_b4ac87_idx'),
        ),
    ]
