# Generated by Django 5.2.7 on 2026-09-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional end-customer account link (Sprint 10A — D-025). Null = guest checkout; ``customer_name`` + ``customer_phone`` remain the snapshot for kitchen display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.customer'),
        ),
    ]
