# Generated by Django 5.2.7 on 2026-09-26 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('price_changed', 'Price changed'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('reordered', 'Reordered')], max_length=30)),
                ('target_type', models.CharField(choices=[('menu', 'Menu'), ('category', 'Category'), ('item', 'Item'), ('branch', 'Branch'), ('theme', 'Theme'), ('organization', 'Organization')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('target_repr', models.CharField(help_text="Human-readable snapshot of the target at event time (e.g. 'Türk Kahvesi (modern-cafe)').", max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Change details — e.g. {'old': '75.00', 'new': '85.00'}.")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null = system-initiated (e.g. seed, cron).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_dbfe04_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx')],
            },
        ),
    ]
