# Generated by Django 5.2.7 on 2026-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('price_changed', 'Price changed'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('reordered', 'Reordered'), ('ai_import_uploaded', 'AI import: PDF uploaded'), ('ai_import_confirmed', 'AI import: draft confirmed'), ('ai_import_discarded', 'AI import: draft discarded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('category', 'Category'), ('item', 'Item'), ('branch', 'Branch'), ('theme', 'Theme'), ('organization', 'Organization'), ('menu_import_draft', 'Menu Import Draft')], max_length=30),
        ),
    ]
