# Generated by Django 5.2.7 on 2026-09-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_plan', models.CharField(choices=[('basic', 'QR Menü Basic'), ('pro', 'QR Menü Pro'), ('orders', 'QR Sipariş'), ('ops', 'Restoran Ops')], default='ops', help_text='Aktif paket — Basic/Pro/Orders/Ops.', max_length=8)),
                ('cart_enabled', models.BooleanField(default=False)),
                ('orders_enabled', models.BooleanField(default=False)),
                ('loyalty_enabled', models.BooleanField(default=False)),
                ('customer_accounts_enabled', models.BooleanField(default=False)),
                ('payments_enabled', models.BooleanField(default=False)),
                ('ai_pdf_import_enabled', models.BooleanField(default=False)),
                ('ai_translate_enabled', models.BooleanField(default=False)),
                ('advanced_analytics_enabled', models.BooleanField(default=False)),
                ('billing_notes', models.TextField(blank=True, default='', help_text='Operator-visible note (coupon applied, manual override, …).')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Plan Ayarları',
                'verbose_name_plural': 'Plan Ayarları',
                'indexes': [models.Index(fields=['organization'], name='billing_pla_organiz_d8cd71_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveSmallIntegerField(help_text='UTC year — e.g. 2026.')),
                ('period_month', models.PositiveSmallIntegerField(help_text='UTC month — 1..12.')),
                ('views', models.PositiveIntegerField(default=0)),
                ('scans', models.PositiveIntegerField(default=0)),
                ('ai_pdf_imports', models.PositiveIntegerField(default=0)),
                ('ai_translate_ops', models.PositiveIntegerField(default=0)),
                ('ai_description_ops', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Aylık Kullanım Sayacı',
                'verbose_name_plural': 'Aylık Kullanım Sayaçları',
                'indexes': [models.Index(fields=['organization', 'period_year', 'period_month'], name='billing_usage_period_idx')],
                'unique_together': {('organization', 'period_year', 'period_month')},
            },
        ),
    ]
