# Generated by Django 5.2.7 on 2026-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansettings',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plansettings',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
