# Generated by Django 5.2.7 on 2026-09-26 11:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.JSONField(default=dict)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alerjen',
                'verbose_name_plural': 'Alerjenler',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.JSONField(default=dict)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diyet Etiketi',
                'verbose_name_plural': 'Diyet Etiketleri',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('default_locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5)),
                ('supported_locales', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='branches.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Menü',
                'verbose_name_plural': 'Menüler',
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ('menu', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MenuCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Kategori Çevirisi',
                'verbose_name_plural': 'Kategori Çevirileri',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('price', models.DecimalField(decimal_places=2, help_text='TRY/EUR/USD cinsinden fiyat. Negatif olamaz (OP-6).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('spice_level', models.PositiveSmallIntegerField(choices=[(0, 'Yok'), (1, 'Hafif'), (2, 'Orta'), (3, 'Acılı')], default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('category', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MenuItemAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='menu.allergen')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allergens', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Ürün → Alerjen',
                'verbose_name_plural': 'Ürün → Alerjen',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='menu_items', through='menu.MenuItemAllergen', to='menu.allergen'),
        ),
        migrations.CreateModel(
            name='MenuItemDietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='menu.dietarytag')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_dietary_tags', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Ürün → Diyet Etiketi',
                'verbose_name_plural': 'Ürün → Diyet Etiketleri',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', through='menu.MenuItemDietaryTag', to='menu.dietarytag'),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Ürün Çevirisi',
                'verbose_name_plural': 'Ürün Çevirileri',
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['organization', 'is_active'], name='menu_menu_organiz_29fbe1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['menu', 'is_active', 'sort_order'], name='menu_menuca_menu_id_77bab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('menu', 'slug')},
        ),
        migrations.AddIndex(
            model_name='menucategorytranslation',
            index=models.Index(fields=['category', 'locale'], name='menu_menuca_categor_9bbcfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategorytranslation',
            unique_together={('category', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemallergen',
            unique_together={('menu_item', 'allergen')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitemdietarytag',
            unique_together={('menu_item', 'dietary_tag')},
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['menu', 'category', 'is_active'], name='menu_menuit_menu_id_3ea95a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'sort_order'], name='menu_menuit_categor_121537_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemtranslation',
            index=models.Index(fields=['menu_item', 'locale'], name='menu_menuit_menu_it_7dae83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemtranslation',
            unique_together={('menu_item', 'locale')},
        ),
    ]
