# Generated by Django 5.2.7 on 2026-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='kcal cinsinden enerji. Örn: 350. Türk Gıda Kodeksi uyumu.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='contains_alcohol',
            field=models.BooleanField(default=False, help_text='Alkol var mı? (Vergi/yasal etiket zorunluluğu)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text="Virgülle ayrılmış içerik listesi. Örn: 'domates, peynir, un'."),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_halal',
            field=models.BooleanField(blank=True, help_text='Helal sertifikası. None=belirtilmemiş, True/False.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='legal_notes',
            field=models.TextField(blank=True, default='', help_text="Alerjen uyarıları + yasal notlar. Örn: 'Buğday, süt, yumurta içerir.'"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='portion_size',
            field=models.CharField(blank=True, default='', help_text="Porsiyon miktarı. Örn: '250g', '1 porsiyon', '350ml'.", max_length=60),
        ),
    ]
