# Generated by Django 5.2.7 on 2026-09-26 10:32

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#1F2937', help_text='Hex renk, #RRGGBB', max_length=7, validators=[apps.core.validators.validate_hex_color])),
                ('secondary_color', models.CharField(default='#F59E0B', max_length=7, validators=[apps.core.validators.validate_hex_color])),
                ('accent_color', models.CharField(default='#10B981', max_length=7, validators=[apps.core.validators.validate_hex_color])),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[apps.core.validators.validate_hex_color])),
                ('text_color', models.CharField(default='#111827', max_length=7, validators=[apps.core.validators.validate_hex_color])),
                ('font_family', models.CharField(choices=[('system', 'System Default'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('playfair', 'Playfair Display')], default='system', max_length=32)),
                ('layout_variant', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('compact', 'Compact')], default='modern', max_length=16)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Tema Ayarları',
                'verbose_name_plural': 'Tema Ayarları',
            },
        ),
    ]
