# Generated by Django 5.2.7 on 2026-09-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp_phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('working_hours_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'ordering': ('organization', 'name'),
                'indexes': [models.Index(fields=['organization', 'is_active'], name='branches_br_organiz_f2174d_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
