# Generated by Django 5.2.7 on 2026-09-29 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='image', max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('storage_key', models.CharField(db_index=True, max_length=500)),
                ('public_url', models.URLField(max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('thumbnail_key', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medya Varlığı',
                'verbose_name_plural': 'Medya Varlıkları',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'kind', 'is_active'], name='media_media_organiz_b3b7ea_idx'), models.Index(fields=['organization', '-created_at'], name='media_media_organiz_5d07b6_idx')],
            },
        ),
    ]
