# Generated by Django 5.2.7 on 2026-09-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=5)),
                ('generated_text', models.TextField()),
                ('ai_provider', models.CharField(max_length=16)),
                ('ai_model', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_descriptions', to='menu.menuitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_descriptions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI Product Description',
                'verbose_name_plural': 'AI Product Descriptions',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['organization', 'locale'], name='translate_a_organiz_6094aa_idx'), models.Index(fields=['menu_item', 'locale'], name='translate_a_menu_it_0224d1_idx')],
                'unique_together': {('menu_item', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='TranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text_hash', models.CharField(help_text='SHA-256 hex of the normalized source text.', max_length=64)),
                ('source_locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=5)),
                ('source_text', models.TextField(blank=True, default='', help_text='Snapshot of the original source (truncated to 500 chars).')),
                ('target_locale', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=5)),
                ('translated_text', models.TextField()),
                ('ai_provider', models.CharField(max_length=16)),
                ('ai_model', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Provider-reported confidence in [0.00, 1.00].', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_memory', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Translation Memory',
                'verbose_name_plural': 'Translation Memories',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'target_locale'], name='translate_t_organiz_4ad8a5_idx'), models.Index(fields=['source_text_hash'], name='translate_t_source__75e652_idx')],
                'unique_together': {('organization', 'source_text_hash', 'target_locale')},
            },
        ),
    ]
