# Generated by Django 5.2.7 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='organizations/covers/')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp_phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('default_locale', models.CharField(default='tr', max_length=8)),
                ('supported_locales', models.JSONField(default=list)),
                ('currency', models.CharField(default='TRY', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'İşletme',
                'verbose_name_plural': 'İşletmeler',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx')],
            },
        ),
    ]
