# Generated by Django 5.2.7 on 2026-09-26 18:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('parsing', 'AI parsing in progress'), ('parsed', 'Parsed, awaiting review'), ('confirmed', 'Confirmed, items saved'), ('discarded', 'Discarded'), ('failed', 'Parse failed')], db_index=True, default='pending', max_length=20)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=30)),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('raw_pdf_filename', models.CharField(max_length=200)),
                ('raw_pdf_size_bytes', models.PositiveIntegerField()),
                ('raw_pdf_path', models.CharField(blank=True, default='', max_length=500)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='AI output normalised to {categories: [...]}.')),
                ('error', models.JSONField(blank=True, default=dict, help_text='Populated when status=failed; ``{code, message}``.')),
                ('confidence_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_drafts', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_import_draft', to='menu.menu')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_drafts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'PDF Import Draft',
                'verbose_name_plural': 'PDF Import Drafts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MenuImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Parsed unit price. Null when the AI couldn't find a price.", max_digits=10, null=True)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('allergens', models.JSONField(blank=True, default=list, help_text='List of allergen codes detected by the AI (e.g. ["gluten"]).')),
                ('dietary_tags', models.JSONField(blank=True, default=list, help_text='List of dietary tag codes (e.g. ["vegan", "popular"]).')),
                ('raw_text', models.TextField(blank=True, default='', help_text='Verbatim line/section from the PDF, kept for traceability.')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pdf_import.menuimportdraft')),
            ],
            options={
                'verbose_name': 'PDF Import Item',
                'verbose_name_plural': 'PDF Import Items',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='menuimportdraft',
            index=models.Index(fields=['organization', '-created_at'], name='pdf_import__organiz_c5dde7_idx'),
        ),
        migrations.AddIndex(
            model_name='menuimportdraft',
            index=models.Index(fields=['organization', 'status'], name='pdf_import__organiz_359912_idx'),
        ),
        migrations.AddIndex(
            model_name='menuimportitem',
            index=models.Index(fields=['draft', 'category_name', 'sort_order'], name='pdf_import__draft_i_f2d35c_idx'),
        ),
    ]
