# Generated by Django 5.2.7 on 2026-09-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('menu', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Kısa açıklama — örn. 'Kasa Önü', 'Bahçe Masa 4'.", max_length=80)),
                ('target_url', models.URLField(help_text="Public menü URL'si; save() tarafından otomatik hesaplanır.", max_length=500)),
                ('table_number', models.CharField(blank=True, default='', help_text='Opsiyonel masa numarası (operasyonel takip için).', max_length=20)),
                ('scan_count', models.PositiveIntegerField(default=0, help_text='Bu QR kod için kaydedilen toplam tarama sayısı.')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='branches.branch')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='menu.menu')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
                'ordering': ('organization', '-created_at'),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='qr_qrcode_organiz_cbfde0_idx'), models.Index(fields=['menu', 'is_active'], name='qr_qrcode_menu_id_d49c33_idx')],
            },
        ),
    ]
